# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='ig-markets-auth',
    version='1.0.6',
    description='Authentication for IG Markets REST and Streaming APIs',
    python_requires='==3.7.*',
    author='Kevin Courbet',
    author_email='kevin.courbet.contact@gmail.com',
    packages=['ig_markets_auth'],
    package_dir={"": "."},
    package_data={},
    install_requires=['attrs', 'httpx', 'loguru', 'pydantic[dotenv,email]'],
    extras_require={"dev": ["autopep8", "flake8", "ipykernel", "pytest"]},
)
